SELECT CATEGORY, PRICE AS MAX_PRICE,PRODUCT_NAME
FROM(
    SELECT *,
    RANK()OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC) RK
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
) RS
WHERE RS.RK = 1
ORDER BY PRICE DESC