select UGB.TITLE, UGB.BOARD_ID,UGR.REPLY_ID,UGR.WRITER_ID, 
UGR.CONTENTS, DATE_FORMAT(UGR.CREATED_DATE,"%Y-%m-%d") as CREATED_DATE
from USED_GOODS_BOARD UGB
join USED_GOODS_REPLY UGR ON UGB.BOARD_ID = UGR.BOARD_ID
where DATE_FORMAT(UGB.CREATED_DATE,"%Y%m") = '202210'
order by UGR.CREATED_DATE ASC, UGB.TITLE ASC