SELECT
    T.FOOD_TYPE, T.REST_ID, T.REST_NAME,T.FAVORITES
FROM (
    SELECT FOOD_TYPE, REST_ID, REST_NAME,FAVORITES,
        ROW_NUMBER() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RN
    FROM REST_INFO
    ) T
WHERE T.RN = 1
ORDER BY T.FOOD_TYPE DESC